services:
    ongr_router.chain_router:
        class: Symfony\Cmf\Component\Routing\ChainRouter
        arguments: [ "@?logger" ]
        calls:
            - [ setContext, [ "@router.request_context" ] ]

    ongr_router.dummy_route_collection:
        class: Symfony\Component\Routing\RouteCollection

    ongr_router.elasticsearch_route_provider:
        class: ONGR\RouterBundle\Routing\ElasticsearchRouteProvider
        arguments:
            - "@es.metadata_collector"
            - [] # Actual map is set by compiler pass

    ongr_router.final_matcher:
        class: Symfony\Cmf\Component\Routing\NestedMatcher\UrlMatcher
        arguments: ["@ongr_router.dummy_route_collection", "@router.request_context"]

    ongr_router.nested_matcher:
        class: Symfony\Cmf\Component\Routing\NestedMatcher\NestedMatcher
        arguments: ["@ongr_router.elasticsearch_route_provider", "@ongr_router.final_matcher"]

    ongr_router.url_generator:
        class: ONGR\RouterBundle\Routing\DocumentUrlGenerator
        arguments: ["@ongr_router.elasticsearch_route_provider", "@?logger"]
        calls:
            - [ setCollector, [ "@es.metadata_collector" ] ]

    ongr_router.symfony_default_router:
        parent: router.default
        tags:
            - { name: router, priority: 100 }

    ongr_router.dynamic_router:
        class: Symfony\Cmf\Component\Routing\DynamicRouter
        arguments: ["@router.request_context", "@ongr_router.nested_matcher", "@ongr_router.url_generator", '', "@event_dispatcher", "@ongr_router.elasticsearch_route_provider"]
