sudo: true
language: php
php:
  - 5.6
  - 7.0
  - hhvm
env:
  global:
    - JAVA_HOME="/usr/lib/jvm/java-8-oracle/jre"
    - ES_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.2.zip"
matrix:
  allow_failures:
    - php: hhvm
addons:
  apt:
    packages:
      - oracle-java8-installer
install:
  - sudo apt-get install -y oracle-java8-set-default
  - curl -L -o elasticsearch.zip $ES_URL
  - unzip elasticsearch.zip
  - ./elasticsearch-*/bin/elasticsearch -d
before_script:
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - composer install --no-interaction --prefer-dist
script:
  - vendor/bin/phpunit --coverage-clover=coveralls.clover
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/,Tests/app/ ./
after_script:
  - travis_retry php vendor/bin/coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/81e47479feba5ba8dc47
    on_success: change
    on_start: never
