language: php
php:
  - 5.4
  - 5.5
  - 5.6
env:
  - SYMFONY="2.6.*"
services:
  - elasticsearch
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - composer install
script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -p --standard=./vendor/ongr/ongr-strict-standard/ONGR --ignore=vendor/,Tests/app/,Resources/public/ ./
