language: php
php:
    - 5.4
    - 5.5
    - 5.6
services:
    - elasticsearch
install:
    - sudo pip install -q sphinx --use-mirrors
    - wget -q -O conf.py https://raw.githubusercontent.com/ongr-io/docs-aggregator/master/source/conf-travis.py
before_script:
    - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
    - composer install
script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
    - vendor/bin/phpcs -p --standard=$TRAVIS_BUILD_DIR/vendor/ongr/ongr-strict-standard/Ongr --ignore=vendor/,Tests/app/,Resources/public/ ./
    - sphinx-build -nWq -b html -c . Resources/doc _build/html
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && wget --post-data="" -q -O /dev/null http://readthedocs.org/build/ongr'
cache:
    directories:
        - vendor/
        - $HOME/.composer/cache
